"""

Revision ID: 27362b801748
Revises: 04e5369d0b88
Create Date: 2026-07-02 23:23:01.781515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27362b801748'
down_revision: Union[str, Sequence[str], None] = '04e5369d0b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_telegram_users_telegram_id'), 'telegram_users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_telegram_users_user_id'), 'telegram_users', ['user_id'], unique=False)
    op.add_column('email_users', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_email_users_id'), table_name='email_users')
    op.create_index(op.f('ix_email_users_user_id'), 'email_users', ['user_id'], unique=False)
    op.drop_constraint(op.f('email_users_id_fkey'), 'email_users', type_='foreignkey')
    op.create_foreign_key(None, 'email_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('email_users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_users', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'email_users', type_='foreignkey')
    op.create_foreign_key(op.f('email_users_id_fkey'), 'email_users', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_email_users_user_id'), table_name='email_users')
    op.create_index(op.f('ix_email_users_id'), 'email_users', ['id'], unique=False)
    op.drop_column('email_users', 'user_id')
    op.drop_index(op.f('ix_telegram_users_user_id'), table_name='telegram_users')
    op.drop_index(op.f('ix_telegram_users_telegram_id'), table_name='telegram_users')
    op.drop_table('telegram_users')
    # ### end Alembic commands ###
